#!/bin/sh

case "$1" in
	start)
		printf "Starting bluetooth (RPi3) ... "
		start-stop-daemon -S -q -m -b -p /var/run/btattach.pid --exec /usr/bin/btattach -- -B /dev/ttyS0 -P bcm -S 3000000 
		start-stop-daemon -S -q -m -b -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd -- 
		#bt-adapter --set Powered on
		echo "done."
		;;
	stop)
		printf "Stopping bluetooth (RPi3) ..."
		start-stop-daemon -K -q -p /var/run/bluetoothd.pid
		start-stop-daemon -K -q -p /var/run/btattach.pid
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac
